org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.21.2)
neo_version=21.1.248
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=flyimpact
mod_name=PoopSky: Flyimpact
mod_license=MIT
mod_version=0.0.2-preview+NeoForge1.21.1
mod_group_id=com.altnoir.flyimpact
mod_authors=Clockcycas
mod_description=Adds extra PoopSky flies, Fly Barrel upgrades, and JEI breeding chest transfer.

poopsky_version=2.1.3+NeoForge1.21.1-hotfix
jei_version=19.43.0.393
patchouli_version=1.21-88-neoforge
sophisticatedcore_version=1.21.1-1.4.90.2299
sophisticatedbackpacks_version=1.21.1-3.25.78.2107
